package shared

// Key constants for the app.
const (
	KeyQuit       = "q"
	KeyForceQuit  = "ctrl+c"
	KeyTab        = "tab"
	KeyShiftTab   = "shift+tab"
	KeyPanel1     = "1"
	KeyPanel2     = "2"
	KeyPanel3     = "3"
	KeyUp         = "up"
	KeyDown       = "down"
	KeyEnter      = "enter"
	KeySpace      = " "
	KeyStage      = "s"
	KeyStageAll   = "S"
	KeyUnstage    = "u"
	KeyDiscard    = "d"
	KeyCommit     = "c"
	KeyAmend      = "a"
	KeyPush       = "p"
	KeyForcePush  = "P"
	KeyRebase     = "r"
	KeyLineSelect = "v"
	KeyNextHunk   = "J"
	KeyPrevHunk   = "K"
	KeyHelp         = "?"
	KeyEscape       = "esc"
	KeyCtrlEnter    = "ctrl+s"
	KeyNewBranch    = "n"
	KeyDeleteBranch = "x"
	KeyPull         = "l"
	KeyIgnore       = "i"
	KeyAddRemote    = "A"
)
